debug = false
logLevel = "DEBUG"
InsecureSkipVerify = true
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[providers.file]
  filename = "traefik.toml"

[tls]
  [tls.certificates]
    [tls.certificates.renj]
      certFile = "/renj.io/ssl/fullchain.cer"
      keyFile = "/renj.io/ssl/ssl.key"
    [tls.certificates.jjapp]
      certFile = "/renj.io/ssl2/fullchain.cer"
      keyFile = "/renj.io/ssl2/ssl.key"

# https域名优先重定向
[http.routers]
  # 正常证书的https认证
  [http.routers.https-renj]
    entryPoints = ["https"]
    rule = "PathPrefix(`/`)"
    middlewares = ["compress", "error", "limit", "customHeader"]
    tls = true
    service = "sandwich"
  # 正常证书的https认证  
  [http.routers.https-jjapp]
    entryPoints = ["https"]
    rule = "Host(`jjapp.dev`)"
    middlewares = ["compress", "error", "limit", "customHeader"]
    tls = true
    service = "sandwich"    
  # http自动重定向  
  [http.routers.http2https]
    entryPoints = ["http"]
    middlewares = ["redirect-to-https", "compress", "error", "limit", "customHeader"]
    rule = "HostRegexp(`((dev|blog|service|page|pkg|x|me).renj.io|^renj.io|jjapp.dev)`)"
    service = "sandwich"
  [http.routers.web]
    entryPoints = ["http"]
    rule = "PathPrefix(`/`)"
    middlewares = ["compress", "error", "limit", "customHeader"]
    service = "sandwich"

[http.services]
  [http.services.sandwich]
    [http.services.sandwich.loadBalancer]
       [[http.services.sandwich.loadBalancer.servers]]
         url = "http://localhost:8888"

[http.middlewares]
  # 重定向https
  [http.middlewares.redirect-to-https]
    [http.middlewares.redirect-to-https.redirectScheme]
      scheme =  "https"
      permanent = true
  # 开启gzip    
  [http.middlewares.compress]
    [http.middlewares.compress.compress]
      excludedContentTypes = ["text/event-stream"]
      minResponseBodyBytes = 2048
      defaultEncoding = "gzip"
  # 错误处理由sandwich处理    
  [http.middlewares.error]
    [http.middlewares.error.errors]
    status = ["404","500","501","503","505-599"]
    service = "sandwich"
  # body体限制 最大100mb  
  [http.middlewares.limit.buffering]
    maxRequestBodyBytes = 10000000
  # 自定义headers  
  [http.middlewares.customHeader.headers]
    [http.middlewares.customHeader.headers.customResponseHeaders]
        X-Gateway-Name = "RainbowBridge"
        Server = ""